# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoted_by',
            field=models.CharField(default='Arthur C Clarke', max_length=255),
            preserve_default=False,
        ),
    ]
