# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-28 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_quote_quoted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='App1.User')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='App1.Quote')),
            ],
        ),
    ]
