# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-28 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_body',
            new_name='quote',
        ),
    ]
