# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-28 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_auto_20190128_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='quote',
            new_name='parent_quote',
        ),
    ]
