# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-30 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_auto_20190128_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='parent_quote',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
