# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-22 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_templates_app', '0002_remove_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Author notes'),
            preserve_default=False,
        ),
    ]
